model_config:
  model_type: rgb
  backbone: resnet18
  rgb_seq_length: 16
  input_type: 3d
  sample_strategy: consecutive 
  dropout_ratio: 0.0
dataset_config:
  label_map:
    Hand_in_Shelf: 0
    Inspect_Product: 1
    Inspect_Shelf: 2
    Reach_to_Shelf: 3
    Retract_from_Shelf: 4

  output_shape:
  - 224
  - 224
  batch_size: 32
  workers: 8
  augmentation_config:
    train_crop_type: no_crop
    horizontal_flip_prob: 0.0
    rgb_input_mean: [0.5]
    rgb_input_std: [0.5]
    val_center_crop: False
